CREATE TABLE IF NOT EXISTS `vrp_ifood_job` (
  `user_id` INT NOT NULL,
  `reputation` INT NOT NULL DEFAULT 0,
  `deliveries` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
